title: Paprikati
description: Engineering blog from paprikati
author: "Lisa Karlin Curtis"


theme: minima

# Minima social links
twitter_username: paprikati_eng
github_username: paprikati
linkedin_username: lisa-karlin-curtis-a4563920

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%-d %b, %Y"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Used by jekyll-seo-tags
twitter:
  username: paprikati_eng

# Google Analytics
google_analytics: UA-199223266-1
